version: "3"
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    image: "mongo"
    volumes:
      - teactactive-db-data:/data/db
    ports:
      - "27018:27017"

volumes:
  teactactive-db-data:
