version: "3"
services:
  backend:
    environment:
      - NODE_ENV=production
    restart: always
    build: .
    secrets:
      - ssl_cert
      - ssl_cert_private_key
    network_mode: "host"

secrets:
  ssl_cert:
    file: /run/secrets/ssl_cert
  ssl_cert_private_key:
    file: /run/secrets/ssl_cert_private_key
